version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    ports:
      - "9200:9200"
    restart: "always"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    container_name: elasticsearch
    networks:
      - default

  kibana:
    image: kibana:7.7.0
    ports:
      - "5601:5601"
    restart: "always"
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - default

  logstash:
    image: logstash:7.7.0
    ports:
      - "4560:4560"
      - "9600:9600"
    restart: "always"
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - default

networks:
  default:
    external:
      name: magi-network



